# Site settings
title: Gezonde Recepten
description: Gezonde en lekkere recepten voor elk moment van de dag

# Build settings
markdown: kramdown

# Collections
collections:
  recepten:
    output: true
    permalink: /recepten/:title/
  reviews:
    output: true
    permalink: /reviews/:title/


# Default front matter for recipes
defaults:
  - scope:
      path: ""
      type: "recepten"
    values:
      layout: recipe
      comments: true

# Include directories
include:
  - _recepten
  - categorie

# Exclude directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor


