# Site settings
title: Gezonde Recepten
description: Gezonde en lekkere recepten voor elk moment van de dag. Ontdek honderden makkelijke, voedzame recepten met stap-voor-stap instructies.
url: "https://www.gezondenmakkelijk.nl"  # voeg dit toe
author: Gezonde & Makkelijk Team
keywords: gezonde recepten, makkelijke recepten, voedzame maaltijden, koolhydraatarm, vegetarisch, meal prep

# Build settings
markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Collections
collections:
  recepten:
    output: true
    permalink: /recepten/:title/
  reviews:
    output: true
    permalink: /reviews/:title/


# Default front matter for recipes
defaults:
  - scope:
      path: ""
      type: "recepten"
    values:
      layout: recipe
      comments: true
      schema_type: Recipe
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: review
      comments: true
      schema_type: Article


# Include directories
include:
  - _recepten
  - categorie

# Exclude directories

# Exclude directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - package.json
  - package-lock.json
  - .gitignore